V1 - 08 12 2024 - script deploy environement ok
invitu/env_invitu_dev pull request #1
Opened 2023-12-08 21:57 UTC by coco-invitu

2023-12-09 03:30 UTC, cvinh requested changes

2023-12-09 03:30 UTC, cvinh commented on launch_project.sh
> +    ;;
please factorize with in 8|9|10...

2023-12-09 03:30 UTC, cvinh commented on launch_project.sh
> +#Read input in the assigned variable
Prompt for 8,9,10... instead of 08,09,10... otherwise it's not compatible with your case statement

2023-12-09 03:30 UTC, cvinh commented on launch_project.sh
> +projectpath="$HOME/invitu-devel/project/$nameproject"
projectpath = $workspacemain/projects/$nameproject

2023-12-09 03:30 UTC, cvinh commented on creation_environement.sh
> +workspacerepos="$HOME/invitu-devel/allrepos"
It should be $workspacemain/allrepos

2023-12-09 03:30 UTC, cvinh commented on creation_environement.sh
> +workspaceodoo="$HOME/invitu-devel/allrepos/gitodoo/odoo"
It should be $workspacerepos/gitodoo

2023-12-09 03:30 UTC, cvinh commented on creation_environement.sh
> +    cd $workspacereposodoo
It should be
mkdir -p $workspaceodoo && cd $workspaceodoo

2023-12-09 03:30 UTC, cvinh commented on creation_environement.sh
> +    git clone https://github.com/odoo/odoo.git
It should be
git clone https://www.github.com/odoo/odoo --depth 1 --branch 17.0 --single-branch

2023-12-09 03:30 UTC, cvinh commented on launch_project.sh
> +## Welcome message
Define
workspacemain = $HOME/invitu-devel
workspacerepos = $workspacemain/allrepos
as you did in create_environment.sh

2023-12-09 03:30 UTC, cvinh commented on launch_project.sh
> +pyenv_name=$nameproject
pyenv_name=odoo$odooversion

2023-12-09 03:30 UTC, cvinh commented on launch_project.sh
> +odoopath="$HOME/invitu-devel/allrepos/gitodoo/odoo"
odoopath=$workspacerepos/gitodoo/odoo

2023-12-09 03:30 UTC, cvinh commented on launch_project.sh
> +echo "On vérifie si le fichier modules.csv existe..."
echo "On se déplace dans le dossier du projet"
cd $projectpath

2023-12-09 03:30 UTC, cvinh commented on launch_project.sh
> +
Please include your treatment in the "if" condition

2023-12-09 03:30 UTC, cvinh commented on creation_environement.sh
> +workspaceproject="$HOME/invitu-devel/project"
It should be $workspacemain/projects

2023-12-11 19:00 UTC, coco-invitu commented on creation_environement.sh
> +workspaceproject="$HOME/invitu-devel/project"
OK

2023-12-11 19:01 UTC, coco-invitu commented on creation_environement.sh
> +    git clone https://github.com/odoo/odoo.git
OK

2023-12-11 19:01 UTC, coco-invitu commented on creation_environement.sh
> +    cd $workspacereposodoo
OK

2023-12-11 19:01 UTC, coco-invitu commented on creation_environement.sh
> +workspaceodoo="$HOME/invitu-devel/allrepos/gitodoo/odoo"
OK

2023-12-11 19:02 UTC, coco-invitu commented on creation_environement.sh
> +workspacerepos="$HOME/invitu-devel/allrepos"
OK

2023-12-11 19:02 UTC, coco-invitu commented on launch_project.sh
> +#Read input in the assigned variable
OK

2023-12-11 19:03 UTC, coco-invitu commented on launch_project.sh
> +## Welcome message
OK

2023-12-11 19:03 UTC, coco-invitu commented on launch_project.sh
> +projectpath="$HOME/invitu-devel/project/$nameproject"
OK

2023-12-11 19:04 UTC, coco-invitu commented on launch_project.sh
> +pyenv_name=$nameproject
OK

2023-12-11 19:05 UTC, coco-invitu commented on launch_project.sh
> +odoopath="$HOME/invitu-devel/allrepos/gitodoo/odoo"
OK

2023-12-11 19:06 UTC, coco-invitu commented on launch_project.sh
> +echo "On vérifie si le fichier modules.csv existe..."
OK

2023-12-11 19:06 UTC, coco-invitu commented on launch_project.sh
> +
WIP today

2023-12-11 19:14 UTC, coco-invitu commented on launch_project.sh
> +    ;;
We search a solution to factorize at the end, in amelioration process. At this time, this structure work without problem.

2023-12-12 19:57 UTC, merged