[IMP] Update README
invitu/env_invitu_dev pull request #2
Opened 2024-10-29 00:24 UTC by vehi-invitu

2024-10-29 00:47 UTC, cvinh requested changes

2024-10-29 00:47 UTC, cvinh commented on README.md
> +### 1. Create repos for your environment
This is not a repos but a workspace on your local environment
Maybe better to explain like this :
This script has been written to have a quickly odoo environment using python env and git stuff.
The workspace on the developer computer should be like this : 
~/invitu-devel/allrepos : all the repos cloned from github
~/invitu-devel/projects : all the projects the developer works on
For example, we can have 3 repos gitodoo, gitoca, gitinvitu respectively https://github.com/odoo/odoo, https://github.com/oca, https://github.com/invitu
For a project named "test" in Odoo v17, we will have  ~/invitu-devel/projects/test17

2024-10-29 00:47 UTC, cvinh commented on README.md
> +mkdir [name_repos]
no need to put the commands mkdir or cd, the reader is supposed to know those commands

2024-10-29 00:47 UTC, cvinh commented on README.md
> +```
in ~/invitu-devel/allrepos/gitinvitu, clone this repo

2024-10-29 00:47 UTC, cvinh commented on README.md
> +vim ~/.bash_profile
no need to put the command vim, the reader is supposed to know it or can use another editor

2024-10-29 00:47 UTC, cvinh commented on README.md
> +1. create a 'modules.csv' file in your project repos (/projects/[project_name])
humm, review please, it's confused

2024-10-29 00:47 UTC, cvinh commented on README.md
> +
explain what is the role of module.csv and explain how to fill it

2024-10-29 00:47 UTC, cvinh commented on README.md
> +```
it's not about module repos here, it's just where to clone the github repos

2024-10-29 00:47 UTC, cvinh commented on README.md
> +dnf install openldap-devel
this has to be done before installing requirements
You forgot to add the export PATH for pgsql binaries

2024-10-29 00:47 UTC, cvinh commented on README.md
> +### Install postgresql/python/openldap : (in repos odoo)
maybe it's no use telling how to install postgresql
but it's a good thing to tell how to install prerequisities for Odoo

2024-10-29 23:32 UTC, cvinh commented on README.md
> +
Please add an example with the url of a pending PR

2024-10-30 00:48 UTC, vehi-invitu commented on README.md
> +### 1. Create repos for your environment
Ok

2024-10-30 00:49 UTC, vehi-invitu commented on README.md
> +mkdir [name_repos]
Ok

2024-10-30 00:49 UTC, vehi-invitu commented on README.md
> +vim ~/.bash_profile
Ok

2024-10-30 00:49 UTC, vehi-invitu commented on README.md
> +1. create a 'modules.csv' file in your project repos (/projects/[project_name])
Ok

2024-10-30 00:49 UTC, vehi-invitu commented on README.md
> +
Ok

2024-10-30 00:49 UTC, vehi-invitu commented on README.md
> +```
Ok

2024-10-30 00:50 UTC, vehi-invitu commented on README.md
> +
Ok

2024-10-30 00:50 UTC, vehi-invitu commented on README.md
> +### Install postgresql/python/openldap : (in repos odoo)
Ok

2024-10-30 01:03 UTC, vehi-invitu commented on README.md
> +dnf install openldap-devel
Ok

2024-10-30 20:19 UTC, vehi-invitu commented on README.md
> +
is it good if I wrote the example like this ? 
2/ module_name,url_branch_PR (access the Pull request(PR) and retrieve the url of the PR source branch)

2024-10-30 20:22 UTC, cvinh commented on README.md
> +
I would have said PR_branch_url
And give an example

2024-10-30 20:25 UTC, vehi-invitu commented on README.md
> +
OK.
The example is this one : (in modules.csv)
> example : vidal_connector,https://github.com/dixmit/connector-vidal/tree/17.0-fix

2024-10-31 00:54 UTC, cvinh approved these changes

2024-10-31 00:54 UTC, merged